Hospital:
  create:
    url: /create
  read:
    url: /read
  update:
    url: /update
  delete:
    url: /delete


Patient:
  create:
    url: /create
  read:
    url: /read
  update:
    url: /update
  delete:
    url: /delete